### ISSUE TITLE
Parsing for JSON blob is too greedy

### ISSUE THREAD

**Issue by pbchase** [ctsit/hide_choice_by_event#3]
The [parsing code](https://github.com/ctsit/hide_choice_by_event/blob/2f13670873ba269147286e3dd37d3699927df70b/ExternalModule.php#L44) that finds the action tag parameter is too greedy. The line reads 

`if (preg_match("/@HIDE-CHOICE-BY-EVENT\s*=\s*(\[.*\])/", $action_tags, $matches)) {`

It uses ']' for its last character in the JSON blob. This works fine if @HIDE-CHOICE-BY-EVENT is the last action tag. e.g.

```
@DEFAULT='R000010104' @DEFAULT_1='[sa3_atorva_dd]'
@HIDE-CHOICE-BY-EVENT = [
    {
        "code": "R000010105",
        "event": ["baseline_arm_1", "followup_month_3_arm_1"]
    }
]
```

Yet it fails if @HIDE-CHOICE-BY-EVENT is followed by an action tag that pipes data.  e.g., 

```
@HIDE-CHOICE-BY-EVENT = [
    {
        "code": "R000010105",
        "event": ["baseline_arm_1", "followup_month_3_arm_1"]
    }
]
@DEFAULT='R000010104' @DEFAULT_1='[sa3_atorva_dd]'
```

These are the same tags in a different order.  In the latter example the "JSON blob" will end with 'sa3_atorva_dd' and fail to parse.

This line would prevent any action tag inclusion

```
if (preg_match("/@HIDE-CHOICE-BY-EVENT\s*=\s*(\[[^@]*\])/", $action_tags, $matches)) {
```
Would the `@` character ever be valid in the JSON?

**Comment by tbembersimeao** [comment]
Fixed by #4.
